language: node_js

node_js:
  - "8"
python:
  - "3.6"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - pip install --user loghub
  - yarn install

script:
  - yarn clean
  - yarn lint
  - yarn build
  - yarn test

deploy:
  - provider: npm
    skip_cleanup: true
    email: ${NPM_USER_EMAIL}
    api_key: ${NPM_USER_API_KEY}
    on:
      tags: true
      repo: ${TRAVIS_REPO_SLUG}
  - provider: releases
    skip_cleanup: true
    api_key: ${GITHUB_TOKEN}
    on:
      tags: true
      repo: ${TRAVIS_REPO_SLUG}
  - provider: script
    skip_cleanup: true
    script: ./script/milestone_changelog.sh > "${TRAVIS_TAG}.changelog" && cat "${TRAVIS_TAG}.changelog" && yarn update_changelog
    on:
      tags: true
      repo: ${TRAVIS_REPO_SLUG}
